apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: elephant
  name: elephant
spec:
  containers:
  - image: polinux/stress
    name: elephant
    resources:
      requests:
        memory: "1Mi"
        cpu: 1
      limits:
        memory: "20Mi"
        cpu: 2
