apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mypage
  name: mypage
spec:
  containers:
  - image: ubuntu:latest
    name: page
    resources:
      requests:
        memory: "1Mi"
        cpu: 1
      limits:
        memory: "10Mi"
        cpu: 2
